service: timeflys-serverless
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  lambdaHashingVersion: '20201221'

functions:
  setCookie:
    handler: handler.setCookie
    events:
      - http:
          path: /api/set-cookie
          method: get
          cors: true
  ping:
    handler: handler.ping
    events:
      - http:
          path: /api/ping
          method: get
          cors: true
  isLoggedIn:
    handler: handler.isLoggedIn
    events:
      - http:
          path: /api/users/isLoggedIn
          method: get
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: /api/users/login
          method: post
          cors: true

